require 'bundler'
Bundler.require

require_relative './manasimu/mana_type.rb'
require_relative './manasimu/card.rb'
require_relative './manasimu/card/basicland.rb'
require_relative './manasimu/card/pathway.rb'
require_relative './manasimu/card/tapland.rb'
require_relative './manasimu/card/slowland.rb'
require_relative './manasimu/card/fetchland.rb'
require_relative './manasimu/card/snc_fetchland.rb'
require_relative './manasimu/planner.rb'
require_relative './manasimu/game.rb'
require_relative './manasimu/simulator.rb'
require_relative './manasimu/data.rb'
require_relative './manasimu/expansion.rb'
require_relative '../ext/ford_fulkerson.so'
